package io.github.bigboyapps.kmpdf

import co.touchlab.kermit.Logger
import kotlinx.coroutines.await
import org.khronos.webgl.Int8Array
import org.khronos.webgl.toByteArray
import org.khronos.webgl.toInt8Array
import kotlin.js.Promise

private val logger = Logger.withTag("KmPdfGenerator")

/** How long a shared PDF stays available, so the browser can finish reading it for the download. */
private const val SHARED_PDF_RELEASE_DELAY_MS = 60_000

/** File names of PDFs generated in this page session, keyed by their blob URL. */
private val fileNamesByUri = mutableMapOf<String, String>()

actual fun createKmPdfGenerator(): KmPdfGenerator = WasmKmPdfGenerator()

/**
 * Browsers have no general share sheet for generated files, so this downloads the PDF
 * using the file name from [PdfConfig].
 *
 * Sharing hands the PDF off to the browser: its memory is freed shortly after the download starts,
 * so [uri] can't be used afterwards. To keep the PDF, use [downloadPdf] or [readPdfBytes] instead
 * and call [releasePdf] when you're done.
 */
actual fun sharePdf(uri: String, title: String) {
    downloadPdf(uri)
    fileNamesByUri.remove(uri)
    revokeObjectUrlLater(uri, SHARED_PDF_RELEASE_DELAY_MS)
}

/**
 * Downloads a PDF generated by [WasmKmPdfGenerator].
 *
 * @param uri The blob URL returned in [PdfResult.Success.uri].
 * @param fileName The name of the downloaded file. Defaults to [PdfConfig.fileName].
 */
fun downloadPdf(uri: String, fileName: String = fileNamesByUri[uri] ?: "document.pdf") {
    try {
        triggerDownload(uri, fileName)
    } catch (e: Throwable) {
        logger.e(e) { "Failed to download PDF: ${e.message}" }
    }
}

actual suspend fun readPdfBytes(uri: String): ByteArray = fetchBytes(uri).await<Int8Array>().toByteArray()

/**
 * Frees the memory held by a generated PDF. The [uri] can't be downloaded or read afterwards.
 *
 * @param uri The blob URL returned in [PdfResult.Success.uri].
 */
fun releasePdf(uri: String) {
    fileNamesByUri.remove(uri)
    revokeObjectUrl(uri)
}

/**
 * Renders each page offscreen, then writes the page images into a PDF held in browser memory.
 *
 * [PdfResult.Success.uri] is a `blob:` URL and [PdfResult.Success.filePath] is the file name,
 * since browsers have no file system to write to.
 */
class WasmKmPdfGenerator : KmPdfGenerator {
    override suspend fun generatePdf(
        config: PdfConfig,
        pages: PdfPageScope.() -> Unit
    ): PdfResult = generatePdfWith(WasmPdfPlatform, config, pages, logger)
}

/** Renders with Skia, compresses with CompressionStream when the browser has it, and keeps PDFs as blobs. */
private object WasmPdfPlatform : SkiaPdfPlatform() {
    private var warnedUncompressed = false

    override suspend fun compress(data: ByteArray): ByteArray? {
        if (!isCompressionStreamSupported()) {
            if (!warnedUncompressed) {
                warnedUncompressed = true
                logger.w { "CompressionStream is unavailable; page images will be stored uncompressed" }
            }
            return null
        }
        return deflate(data.toInt8Array()).await<Int8Array>().toByteArray()
    }

    override suspend fun save(pdf: ByteArray, config: PdfConfig, pageCount: Int): PdfResult.Success {
        val uri = createPdfObjectUrl(pdf.toInt8Array())
        fileNamesByUri[uri] = config.fileName
        return PdfResult.Success(
            uri = uri,
            filePath = config.fileName,
            fileSize = pdf.size.toLong(),
            pageCount = pageCount
        )
    }
}

@JsFun("() => typeof CompressionStream !== 'undefined'")
private external fun isCompressionStreamSupported(): Boolean

// The "deflate" format is zlib-wrapped, which is exactly what PDF's FlateDecode expects
@JsFun(
    """(bytes) => new Response(new Blob([bytes]).stream().pipeThrough(new CompressionStream('deflate')))
        .arrayBuffer()
        .then((buffer) => new Int8Array(buffer))"""
)
private external fun deflate(bytes: Int8Array): Promise<JsAny?>

@JsFun("(bytes) => URL.createObjectURL(new Blob([bytes], { type: 'application/pdf' }))")
private external fun createPdfObjectUrl(bytes: Int8Array): String

@JsFun("(url) => URL.revokeObjectURL(url)")
private external fun revokeObjectUrl(url: String)

@JsFun("(url, delayMs) => { setTimeout(() => URL.revokeObjectURL(url), delayMs); }")
private external fun revokeObjectUrlLater(url: String, delayMs: Int)

@JsFun(
    """(url, fileName) => {
        const anchor = document.createElement('a');
        anchor.href = url;
        anchor.download = fileName;
        anchor.style.display = 'none';
        document.body.appendChild(anchor);
        anchor.click();
        anchor.remove();
    }"""
)
private external fun triggerDownload(url: String, fileName: String)

@JsFun(
    """(url) => fetch(url)
        .then((response) => {
            if (!response.ok) throw new Error("Couldn't read the PDF: HTTP " + response.status);
            return response.arrayBuffer();
        })
        .then((buffer) => new Int8Array(buffer))"""
)
private external fun fetchBytes(url: String): Promise<JsAny?>
