package io.github.bigboyapps.kmpdf

import androidx.compose.runtime.Composable
import androidx.compose.ui.ImageComposeScene
import androidx.compose.ui.unit.Density
import co.touchlab.kermit.Logger
import kotlinx.coroutines.await
import org.jetbrains.skia.Bitmap
import org.jetbrains.skia.ColorAlphaType
import org.jetbrains.skia.ColorType
import org.jetbrains.skia.Image
import org.jetbrains.skia.ImageInfo
import org.khronos.webgl.Int8Array
import org.khronos.webgl.toByteArray
import org.khronos.webgl.toInt8Array
import kotlin.coroutines.cancellation.CancellationException
import kotlin.js.Promise

private val logger = Logger.withTag("KmPdfGenerator")

/** How long a shared PDF stays available, so the browser can finish reading it for the download. */
private const val SHARED_PDF_RELEASE_DELAY_MS = 60_000

/** File names of PDFs generated in this page session, keyed by their blob URL. */
private val fileNamesByUri = mutableMapOf<String, String>()

actual fun createKmPdfGenerator(): KmPdfGenerator = WasmKmPdfGenerator()

/**
 * Browsers have no general share sheet for generated files, so this downloads the PDF
 * using the file name from [PdfConfig].
 *
 * Sharing hands the PDF off to the browser: its memory is freed shortly after the download starts,
 * so [uri] can't be used afterwards. To keep the PDF, use [downloadPdf] or [readPdfBytes] instead
 * and call [releasePdf] when you're done.
 */
actual fun sharePdf(uri: String, title: String) {
    downloadPdf(uri)
    fileNamesByUri.remove(uri)
    revokeObjectUrlLater(uri, SHARED_PDF_RELEASE_DELAY_MS)
}

/**
 * Downloads a PDF generated by [WasmKmPdfGenerator].
 *
 * @param uri The blob URL returned in [PdfResult.Success.uri].
 * @param fileName The name of the downloaded file. Defaults to [PdfConfig.fileName].
 */
fun downloadPdf(uri: String, fileName: String = fileNamesByUri[uri] ?: "document.pdf") {
    try {
        triggerDownload(uri, fileName)
    } catch (e: Throwable) {
        logger.e(e) { "Failed to download PDF: ${e.message}" }
    }
}

/**
 * Reads the bytes of a PDF generated by [WasmKmPdfGenerator], e.g. to upload it.
 *
 * @param uri The blob URL returned in [PdfResult.Success.uri].
 */
suspend fun readPdfBytes(uri: String): ByteArray = fetchBytes(uri).await<Int8Array>().toByteArray()

/**
 * Frees the memory held by a generated PDF. The [uri] can't be downloaded or read afterwards.
 *
 * @param uri The blob URL returned in [PdfResult.Success.uri].
 */
fun releasePdf(uri: String) {
    fileNamesByUri.remove(uri)
    revokeObjectUrl(uri)
}

/**
 * Renders each page offscreen, then writes the page images into a PDF held in browser memory.
 *
 * [PdfResult.Success.uri] is a `blob:` URL and [PdfResult.Success.filePath] is the file name,
 * since browsers have no file system to write to.
 */
class WasmKmPdfGenerator : KmPdfGenerator {
    override suspend fun generatePdf(
        config: PdfConfig,
        pages: PdfPageScope.() -> Unit
    ): PdfResult {
        logger.logDebug { "Starting PDF generation: ${config.fileName}" }

        val pageScope = PdfPageScope()
        pageScope.pages()
        val pageContents = pageScope.pages

        if (pageContents.isEmpty()) {
            return PdfResult.Error.Unknown("No pages provided")
        }

        // Page dimensions in points
        val widthPt = config.pageSize.width.value
        val heightPt = config.pageSize.height.value

        // Use 2x scale for rendering quality
        val scale = 2f
        val pageWidthPx = (widthPt * scale).toInt()
        val pageHeightPx = (heightPt * scale).toInt()

        val compress = isCompressionStreamSupported()
        if (!compress) {
            logger.w { "CompressionStream is unavailable; page images will be stored uncompressed" }
        }

        logger.logDebug { "Page size: ${widthPt}x${heightPt}pt (${pageWidthPx}x${pageHeightPx}px at ${scale}x)" }

        val writer = RasterPdfWriter(widthPt, heightPt)

        pageContents.forEachIndexed { index, pageContent ->
            logger.logDebug { "Rendering page ${index + 1} of ${pageContents.size}" }

            val rgb = try {
                renderPageToRgb(pageContent, pageWidthPx, pageHeightPx, Density(scale))
            } catch (e: Throwable) {
                logger.e(e) { "Failed to render page ${index + 1}: ${e.message}" }
                return PdfResult.Error.RenderingFailed("Failed to render page ${index + 1}: ${e.message}", e)
            }

            val data = try {
                if (compress) deflate(rgb.toInt8Array()).await<Int8Array>().toByteArray() else rgb
            } catch (e: CancellationException) {
                throw e
            } catch (e: Throwable) {
                logger.e(e) { "Failed to compress page ${index + 1}: ${e.message}" }
                return PdfResult.Error.IOError("Failed to compress page ${index + 1}: ${e.message}", e)
            }

            writer.addPage(RasterPdfWriter.PageImage(pageWidthPx, pageHeightPx, data, flateCompressed = compress))
        }

        return try {
            val pdfBytes = writer.build()
            val uri = createPdfObjectUrl(pdfBytes.toInt8Array())
            fileNamesByUri[uri] = config.fileName

            logger.logInfo { "PDF generation successful: ${config.fileName} (${writer.pageCount} pages, ${pdfBytes.size} bytes)" }
            PdfResult.Success(
                uri = uri,
                filePath = config.fileName,
                fileSize = pdfBytes.size.toLong(),
                pageCount = writer.pageCount
            )
        } catch (e: Throwable) {
            logger.e(e) { "Failed to generate PDF: ${e.message}" }
            PdfResult.Error.IOError("Failed to generate PDF: ${e.message}", e)
        }
    }

    private fun renderPageToRgb(
        content: @Composable () -> Unit,
        width: Int,
        height: Int,
        density: Density
    ): ByteArray {
        val scene = ImageComposeScene(
            width = width,
            height = height,
            density = density,
            content = content
        )
        val image = try {
            scene.render()
        } finally {
            scene.close()
        }

        return try {
            image.toRgbOnWhite()
        } finally {
            image.close()
        }
    }
}

/**
 * Reads the image as RGB bytes, flattening transparent areas onto a white page.
 */
private fun Image.toRgbOnWhite(): ByteArray {
    val bitmap = Bitmap()
    try {
        bitmap.allocPixels(ImageInfo(width, height, ColorType.RGBA_8888, ColorAlphaType.PREMUL))
        check(readPixels(bitmap, 0, 0)) { "Failed to read rendered page pixels" }
        val rgba = bitmap.readPixels() ?: error("Failed to read rendered page pixels")

        val rgb = ByteArray(width * height * 3)
        var src = 0
        var dst = 0
        while (dst < rgb.size) {
            // With premultiplied alpha, compositing over white is color + (255 - alpha)
            val background = 255 - (rgba[src + 3].toInt() and 0xFF)
            rgb[dst] = ((rgba[src].toInt() and 0xFF) + background).toByte()
            rgb[dst + 1] = ((rgba[src + 1].toInt() and 0xFF) + background).toByte()
            rgb[dst + 2] = ((rgba[src + 2].toInt() and 0xFF) + background).toByte()
            src += 4
            dst += 3
        }
        return rgb
    } finally {
        bitmap.close()
    }
}

@JsFun("() => typeof CompressionStream !== 'undefined'")
private external fun isCompressionStreamSupported(): Boolean

// The "deflate" format is zlib-wrapped, which is exactly what PDF's FlateDecode expects
@JsFun(
    """(bytes) => new Response(new Blob([bytes]).stream().pipeThrough(new CompressionStream('deflate')))
        .arrayBuffer()
        .then((buffer) => new Int8Array(buffer))"""
)
private external fun deflate(bytes: Int8Array): Promise<JsAny?>

@JsFun("(bytes) => URL.createObjectURL(new Blob([bytes], { type: 'application/pdf' }))")
private external fun createPdfObjectUrl(bytes: Int8Array): String

@JsFun("(url) => URL.revokeObjectURL(url)")
private external fun revokeObjectUrl(url: String)

@JsFun("(url, delayMs) => { setTimeout(() => URL.revokeObjectURL(url), delayMs); }")
private external fun revokeObjectUrlLater(url: String, delayMs: Int)

@JsFun(
    """(url, fileName) => {
        const anchor = document.createElement('a');
        anchor.href = url;
        anchor.download = fileName;
        anchor.style.display = 'none';
        document.body.appendChild(anchor);
        anchor.click();
        anchor.remove();
    }"""
)
private external fun triggerDownload(url: String, fileName: String)

@JsFun("(url) => fetch(url).then((response) => response.arrayBuffer()).then((buffer) => new Int8Array(buffer))")
private external fun fetchBytes(url: String): Promise<JsAny?>
