name: Code Quality

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Detekt
      run: ./gradlew detekt --no-configuration-cache

    - name: Upload Detekt reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: detekt-reports
        path: |
          build/reports/detekt/
          **/build/reports/detekt/

    - name: Annotate PR with Detekt findings
      if: always() && github.event_name == 'pull_request'
      uses: github/super-linter/slim@v5
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_KOTLIN_DETEKT: true

  api-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Check API compatibility
      run: ./gradlew apiCheck --no-configuration-cache

    - name: Upload API check reports
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: api-check-reports
        path: |
          **/api/*.api

  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Generate documentation
      run: ./gradlew dokkaHtml --no-configuration-cache

    - name: Upload documentation
      uses: actions/upload-artifact@v4
      with:
        name: api-docs
        path: build/dokka/html/
